server:
  port: 8083

spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
            value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

          json.value.default.type: com.paypal.notification_service.dto.TransactionEvent
          json.trusted.packages: com.paypal.notification_service.dto

  datasource:
    url: jdbc:h2:mem:noticationDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
#    url: jdbc:mysql://localhost:3306/notificationDB
#    username: root
#    password: password123

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true