server:
  port: 8082

spring:
  application:
    name: transaction-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

api:
  gateway:
    base-url: http://api-gateway:80/transaction-service
