server:
  port: 8080

spring:
  application:
    name: api-gateway-service

  redis:
    host: redis
    port: 6379

  cloud:
    gateway:
      httpClient:
        connect-timeout: 5000
        response-timeout: 5s

  httpclient:
    max-initial-line-length: 4096
    max-header-size: 8192
  filters:
    - name: RequestSize
      args:
        maxSize: 1MB

security:
  jwt:
    secret: "y5x8ZrQF0V6pN8yM7A6e5zT2B3C1XvKpLkU2nH9Jc0A="