apiVersion: apps/v1
kind: Deployment
metadata:
  name: reward-service
  labels:
    app: reward-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reward-service
  template:
    metadata:
      name: reward-service
      labels:
        app: reward-service
    spec:
      containers:
        - name: reward-service
          image: reward-service:1.0
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
              protocol: TCP
      restartPolicy: Always
      