apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  labels:
    app: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      name: transaction-service
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: transaction-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: K8s
      restartPolicy: Always
      