apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"kafka","component":"kafka"},"name":"kafka","namespace":"default"},"spec":{"clusterIP":"None","ports":[{"name":"client","port":9092,"protocol":"TCP","targetPort":9092}],"selector":{"app":"kafka"}}}
  creationTimestamp: "2026-04-30T21:46:05Z"
  labels:
    app: kafka
    component: kafka
  name: kafka
  namespace: default
  resourceVersion: "143015"
  uid: 4f6561b8-8647-459c-8438-8313fedbecd6
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: client
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
  sessionAffinity: None
  type: ClusterIP
