apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallet-service
  namespace: backend
  labels:
    app: wallet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-service
  template:
    metadata:
      name: wallet-service
      labels:
        app: wallet-service
    spec:
      containers:
        - name: wallet-service
          image: wallet-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
              protocol: TCP
          envFrom:
            - configMapRef:
                name: app-env
            - secretRef:
                name: jwt-secret

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      