apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  namespace: backend
spec:
  selector:
    app: wallet-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
  