apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: backend
spec:
  clusterIP: None
  selector:
    app: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: 2181
  